
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: 14-04-2022
  region: ap-south-1

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: 
      publicKeyName: shijinanikhil
      
